version: '2'
services:
    round_robin:
        build:
            context: .
            dockerfile: DockerFile2
        container_name: round_robin
        networks:
            net:
                ipv4_address: 172.24.0.6
        ports:
            - "35004:6000"
    web1:
        image: sparkdocker
        container_name: web1
        networks:
            net:
                ipv4_address: 172.24.0.2
        ports:
            - "35001:6000"
    web2:
        image: sparkdocker
        container_name: web2
        networks:
            net:
              ipv4_address: 172.24.0.3
        ports:
            - "35002:6000"
    web3:
        image: sparkdocker
        container_name: web3
        networks:
            net:
                ipv4_address: 172.24.0.4
        ports:
            - "35003:6000"
    db:
        image: mongo:3.6.1
        container_name: db
        networks:
            net:
                ipv4_address: 172.24.0.5
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: 172.24.0.0/16     
volumes:
    mongodb:
    mongodb_config:

